title: "TriviaMazing"
email: myyogyvd
timezone: UTC
baseurl: "https://www.triviamazing.info"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Ruby
paginate: 30
disqus: 'ruby-6'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-2SHF0BWF65

# Authors
authors:
  Ruby:
    name: Ruby
    display_name: Ruby
    avatar: 'assets/images/ruby.jpg'
    email: rubylyn31429@gmail.com
    web: https://www.rubbiesvlog.xyz
    twitter: 
    description: "Ruby is An Editor, covering tech, entertaining, how-to, crafting, gardening, and deals."
   

# Social
social:
  instagram: https://www.instagram.com/rubbiesvlog
  facebook: https://www.facebook.com/rubbiesvlog
 


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives